before_install:
  - openssl aes-256-cbc -K $encrypted_92dec653b60f_key -iv $encrypted_92dec653b60f_iv -in deploy_key.enc -out deploy_key -d
install: true
script:
  - eval "$(ssh-agent -s)"
  # - echo -e $RESIN_DEPLOY_KEY > id_rsa
  # - chmod 0600 id_rsa
  # - ssh-add ./id_rsa
  - ssh-add ./deploy_key
  - cat resin-host-key >> ~/.ssh/known_hosts
  - git remote add resin $RESIN_REMOTE
  - git push resin master
